version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      go-deps:
        patterns: ["*"]
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      gha-deps:
        patterns: ["*"]
    open-pull-requests-limit: 5
